### ISSUE TITLE
can you make script as well for tamper monkey? please

### ISSUE THREAD

**Issue by mycal123** [thisRaptori/harmony#18]
i appreciate your extension if there's an alternativeof extension, people will more appreciate on greasyfork😌

**Comment by thisRaptori** [comment]
Thanks, glad it's useful for you!

Yeah people might appreciate it, but since I wouldn't personally install an extension which gets access to all sites by default, I wouldn't be able to test it - and I wouldn't have time to maintain two versions either way. Thanks for the suggestion though!
